#!/bin/bash
# =============================================================================
# set-database-url.sh
# =============================================================================
# Run this AFTER `cdk deploy RagAgentDatabase`.
#
# The RDS password is auto-generated by CDK and stored in Secrets Manager
# under a name like "RagAgentDatabase-DatabaseSecret-XXXXXX".
# This script finds it automatically and builds the DATABASE_URL.
#
# HOW TO RUN:
#   chmod +x scripts/set-database-url.sh
#   ./scripts/set-database-url.sh
# =============================================================================

set -e

REGION="${AWS_REGION:-ca-central-1}"

echo "Looking up RDS endpoint and password from CDK outputs..."

# Get the RDS endpoint from CloudFormation outputs
DB_HOST=$(aws cloudformation describe-stacks \
  --stack-name RagAgentDatabase \
  --query "Stacks[0].Outputs[?OutputKey=='DbEndpoint'].OutputValue" \
  --output text \
  --region "$REGION")

if [ -z "$DB_HOST" ]; then
  echo "ERROR: Could not find RagAgentDatabase stack output 'DbEndpoint'."
  echo "Make sure you have run: cdk deploy RagAgentDatabase"
  exit 1
fi

echo "  RDS endpoint: $DB_HOST"

# Get the auto-generated password from the CDK-created secret
DB_SECRET_ARN=$(aws cloudformation describe-stacks \
  --stack-name RagAgentDatabase \
  --query "Stacks[0].Outputs[?OutputKey=='DbSecretArn'].OutputValue" \
  --output text \
  --region "$REGION")

DB_PASS=$(aws secretsmanager get-secret-value \
  --secret-id "$DB_SECRET_ARN" \
  --query "SecretString" \
  --output text \
  --region "$REGION" | python3 -c "import sys,json; print(json.load(sys.stdin)['password'])")

DATABASE_URL="postgresql://ragagent:${DB_PASS}@${DB_HOST}:5432/ragagent"

# Upsert the rag-agent/database-url secret
if aws secretsmanager describe-secret --secret-id "rag-agent/database-url" --region "$REGION" &>/dev/null; then
  aws secretsmanager put-secret-value \
    --secret-id "rag-agent/database-url" \
    --secret-string "$DATABASE_URL" \
    --region "$REGION" > /dev/null
  echo "✓ rag-agent/database-url updated"
else
  aws secretsmanager create-secret \
    --name "rag-agent/database-url" \
    --description "PostgreSQL connection string for the application" \
    --secret-string "$DATABASE_URL" \
    --region "$REGION" > /dev/null
  echo "✓ rag-agent/database-url created"
fi

echo ""
echo "Done. Now run: cdk deploy RagAgentApp"
